# Generated by Django 4.2 on 2025-06-14 09:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('shop_name', models.CharField(max_length=255)),
                ('shop_type', models.CharField(choices=[('normal', 'Normal'), ('shopee_mall', 'Shopee Mall')], default='normal', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('logo', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('public_key', models.TextField(blank=True)),
                ('private_key_hash', models.TextField(blank=True)),
                ('digital_certificate', models.TextField(blank=True)),
                ('signature_algorithm', models.CharField(default='CRYSTAL-DILITHIUM', max_length=50)),
                ('dilithium_variant', models.CharField(default='DILITHIUM3', max_length=20)),
                ('quantum_resistant', models.BooleanField(default=True)),
                ('key_created_at', models.DateTimeField(blank=True, null=True)),
                ('certificate_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_signature_verified', models.BooleanField(default=False)),
                ('business_license', models.TextField(blank=True)),
                ('tax_code', models.CharField(blank=True, max_length=50)),
                ('legal_representative', models.CharField(blank=True, max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sellers',
            },
        ),
    ]
