# Generated by Django 4.2 on 2025-06-14 09:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateAuthority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('public_key', models.TextField()),
                ('certificate', models.TextField()),
                ('algorithm', models.CharField(default='CRYSTAL-DILITHIUM', max_length=50)),
                ('dilithium_variant', models.CharField(default='DILITHIUM3', max_length=20)),
                ('security_level', models.IntegerField(default=3)),
                ('is_trusted', models.BooleanField(default=True)),
                ('is_quantum_resistant', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'certificate_authorities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignatureLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('order', 'Order'), ('payment', 'Payment')], max_length=20)),
                ('entity_id', models.UUIDField()),
                ('action', models.CharField(choices=[('key_generated', 'Key Generated'), ('signature_created', 'Signature Created'), ('signature_verified', 'Signature Verified')], max_length=50)),
                ('signature_algorithm', models.CharField(blank=True, max_length=50)),
                ('dilithium_variant', models.CharField(blank=True, max_length=20)),
                ('signature_data', models.TextField(blank=True)),
                ('signature_size', models.IntegerField(blank=True, null=True)),
                ('verification_result', models.BooleanField(blank=True, null=True)),
                ('quantum_resistant', models.BooleanField(default=False)),
                ('security_level', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'signature_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
